rmohr/bazeldnf

- pkg/rpm/tar_test.go
This makes it possible to successfully run `make test` inside an arbitrary environment.
> Fix tar_test

- BUILD.bazel
The example in the WORKSPACE file was not up-to-date.
> Fix WORKSPACE example

- cmd/ldd.go
If the ld-* lib on the node is not compatible with the libc version
coming in via bazeldnf, we have to use `ld-*` from the pulled in RPMs.
Otherwise we get linker errors.
Signed-off-by: Roman Mohr <rmohr@redhat.com>
> Add ld-* libs to shared library dependencies

- cmd/BUILD.bazel
- cmd/resolve.go
- cmd/rpmtree.go
- cmd/template/BUILD.bazel
- cmd/template/install.go
- pkg/api/api.go
- pkg/sat/sat.go
- pkg/sat/sat_test.go
Allow matching packages with regular expression which should be used
during to solution phase, but not install during the install phase.
Matched packages will be added to the dependency tree, but all their
requirements are wiped. Finally they are excluded from the list of
packages to install too.
Indirect dependencies of an ignored package can still be pulled in by
dependencies of other packages.
The regex can be passed in via `--force-ignore-with-dependencies`:
```bash
$ resolve --nobest -f centos-stream-release --force-ignore-with-dependencies '^kernel-' --force-ignore-with-dependencies '^python[3]{0,1}-' libguestfs
```
In addition a nicer install table will be printed for the `resolve` and the `rpmtree` commands. An example looks like this:
```bash
$ resolve --nobest -f …
```
> Add an option to ignore packages and their dependencies

- cmd/ldd.go
This reverts commit 7db64a1cedfa6efcd034236dbcc15ebba9e84f94 which stopped filter out the linker. If we directly load the linker we potentially end up with two different linkers providing symbols which causes issues.
> Revert "Add ld-* libs to shared library dependencies"

- cmd/init.go
- cmd/reduce.go
- cmd/resolve.go
- cmd/rpmtree.go
- pkg/reducer/reducer.go
Now that CentOS Stream support is fairly solid, hard-coded references to Fedora are increasingly out of place.
> Generalize by removing most Fedora mentions

- cmd/BUILD.bazel
- cmd/ldd.go
- cmd/root.go
- cmd/sandbox.go
- internal/bazeldnf.bzl
- pkg/rpm/tar.go
* Include `ld-*` libraries (this time here to stay)
* Add a `bazeldnf sandbox` command which works similar to untar but without `tar`.
* Fix a few untar issues for `bazeldnf sandbox`
* Allow running the `sandbox` command via the `bazeldnf` rule
* Properly pull in `rpmtree` dependencies in the `bazeldnf` rule which fixes an issue where outdated or not tar files were found.
> Prepare bazeldnf for creating sandboxes for bazel

- pkg/rpm/tar.go
Before this one could only see that creating the hardlink failed, but not why it failed.
> Collect acutal error when creating hard links fails

- internal/runner.bash.template
As described here https://stackoverflow.com/a/7577209 before bash 4.4 there's
a bug where if the array is empty then it's not properly initialize, which
leads to `set -u` trigger an unbounded variable error. Some Linux distributions
like CentOS7 bundle ancient versions like 4.2.46.
It's a minor bug, that's why I didn't created an Issue for it, but let me know if you need one
> [bug] Protect against pre bash 4.4 bug

- WORKSPACE
Otherwise `make all` fails as follows:
ERROR: no such package '@com_google_protobuf//': java.io.IOException: Error extracting /home/maya/.cache/bazel/_bazel_maya/b86cf3d8b83d93fbb749bb3c64493c4b/external/com_google_protobuf/temp11108607076077878807/master.zip to /home/maya/.cache/bazel/_bazel_maya/b86cf3d8b83d93fbb749bb3c64493c4b/external/com_google_protobuf/temp11108607076077878807: Prefix "protobuf-master" was given, but not found in the archive. Here are possible prefixes for this archive: "protobuf-main".
> Follow protobuf branch s/master/main/ - otherwise we fail to fetch it

- internal/runner.bash.template
After the recent changes to the way bash arrays are used, if you have a rule like
```
bazeldnf(
name = "ldd_test",
command = "ldd",
...
)
```
then calling
```
$ bazel run //:ldd_test
```
will result in
```
Error: unknown command "\"ldd" for "bazeldnf"
```
This is caused by the excessive number of (nested, escaped) quotes that are present in the expression. The new version follows the recommendations from https://stackoverflow.com/questions/7577052/ accurately and as such doesn't exhibit the problem.
> Fix usage of bash arrays

- cmd/ldd.go
- pkg/ldd/ldd.go
On current aarch64 Linux versions such as CentOS Stream 9 and Fedora 36, `ld-linux-aarch64.so` is found in `/usr/lib` instead of `/usr/lib64`.
> Look for libraries in /usr/lib too

- pkg/bazel/bazel.go
Recent builds of passt ([list](https://copr.fedorainfracloud.org/coprs/sbrivio/passt/builds/)) use version numbers like
```
0^20221015.gb3f3591-1
0^20221014.gdf73bb1-1
0^20220929.g06aa26f-1
```
which is entirely correct from the RPM point of view but requires special care on the bazel front. While at it, deal with tilde too.
> Sanitize RPM names further

- cmd/rpmtree.go
- pkg/bazel/bazel.go
This will remove the need to have workarounds like https://github.com/kubevirt/kubevirt/commit/8052a7f3e30b221550bc8d49d74b77eaf5b4998a in the future.
> Escape URLs before adding them to bazel rules

- cmd/BUILD.bazel
- cmd/prune.go
- cmd/rpmtree.go
- cmd/verify.go
- pkg/bazel/bazel.go
- pkg/bazel/bazel_test.go
- pkg/bazel/testdata/orig.bzl
- pkg/bazel/testdata/pkgs.bzl
Closes #26.
This PR adds a new flag `--to_macro` (or `--from_macro` for verify), that uses a macro in a bzl file instead of the WORKSPACE for `rpm` rules.
The flag expects an expression of the form `path/to/file.bzl%name`, where the path to the bzl file and the name of the macro are separated by `%`.
I'm new to using bazel buildtools so I apologize for potentially weird choices.
> implement to_macro as alternative destination for rpm rules

- cmd/BUILD.bazel
Resolves #45
From @fmeum on Slack with regards to using bazeldnf as a provider for cross compiler toolchain sysroots:
> The Bazel DNF tool appears to be a Go tool. By default, on supported platforms, Go tools use a standard library built with a C compiler (cgo), which causes the cyclic dependency on the C++ toolchain.
> If @bazeldnf//cmd:cmd set pure = True on the go_binary rule, that may resolve this cyclic dependency.
While this issue is also fixed by shipping pre-compiled binaries, marking the binary as pure should be generally preferred since it has less dependencies on the host system (libc).
> mark bazeldnf as pure go binary

- cmd/rpm2tar.go
- pkg/rpm/cpio2tar.go
- pkg/rpm/tar.go
- pkg/rpm/tar_test.go
Fixes #47
<strike>While this fixes my immediate issue, it's not very clean to pass around a map that is filled with state between invocations of `Tar`. The function was quite functional before.
Happy to refactor this to be cleaner. Just not quite sure where to go.</strike>
I can stay on this commit for the time being so there is no reason to rush merging this.
> skip duplicate files in rpms

- README.md
- hack/prepare-release.sh
Since `deps.bzl` now contains prebuilt images, there is no need to set up a golang toolchain to use bazeldnf from within bazel.
This PR will anso ensure that future release runs will also update the README.md file with the correct installation instructions.
> Update README to reflect the golang dependency drop

- README.md
- hack/prepare-release.sh
If a release candidate is built (`-rc` in the version string), then don't update the README.md install instructions, so that people always see the last valid release.
> Support release candidate bulding properly

- internal/rpm.bzl
- internal/rpmtree.bzl
Two small changes:
This is an alternative format for specifying the expected hash. It specifies the expected checksum in [Subresource Integrity format](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) of the file downloaded.
When using remote cache in Bazel, some IO intensive actions are slower when using the remote cache (vs always redoing the action locally). This behavior can be controlled using the flag `--modify_execution_info`.
See also: https://blog.aspect.dev/bazelrc-flags
> RPM rule integrity and mnemonics

- pkg/repo/fetch.go
In a repo.yaml file, instead of just the http:// or https:// scheme, the user might want to specify a local path for an repo, e.g.
repositories:
- arch: x86_64
baseurl: file:///RPMS
name: local
And then use that with fetch, e.g.
% bazeldnf fetch
INFO[0000] Resolving repomd.xml from file:///RPMS/repodata/repomd.xml
INFO[0000] Loading primary file from file:///RPMS/repodata/<HASH>-primary.xml.gz
To address this, update the Getter implementation to parse the URL using net/url Parse, and the call a handler that opens a local file and returns a wrapper http.Response when the scheme is "file".
> Support file:// scheme for repo URLs

- pkg/repo/BUILD.bazel
- pkg/repo/fetch_test.go
Pull request #63 added support for the `file://` scheme for `fetch`. This change adds the suggested test case to ensure that both the baseline `http://` support and the newly-added `file://` support are working as expected.
> Add unit test for repo.getterImpl (and file:// scheme support)

- pkg/bazel/bazel.go
- pkg/bazel/testdata/WORKSPACE
Currently if for some reason the RPM entry changed, bazeldnf won't reconfigure the URLs if they are already set. While this behavior aims to cover cases like mirror urls getting added out of band, there is a case where the URLs are messed up and do match the checksum. Therefore with this change it reconfigures the RPM URLs when the checksum changed.
> Reconfigure the RPM URLs if checksum changed.

- internal/rpmtree.bzl
The names that are passed to bazeldnf need to include the directory part too, otherwise having two files with the same name in different paths triggers a failure:
```
+ bazel run --config x86_64 //rpm:sandbox_s390x
...
Error in _tar2files: generated file 'cc-toolchain_s390x/errno.h'
in rule 'cc-toolchain_s390x/usr/include/asm' conflicts with
existing generated file from rule 'cc-toolchain_s390x/usr/include'
```
> Fix tar2files bazel integration

- cmd/BUILD.bazel
- hack/prepare-release.sh
Add s390x to build targets.
I would like to add s390x support for this project, as it is a required dependency to [enable kubevirt](https://github.com/kubevirt/kubevirt/pull/10490) for s390x.
There is not really anything else needed to be done for this. I did not find any tests or CI that would need changes.
Please let me know if there are any other required changes that i missed or if there are any question.
> Enable support for s390x architecture

- Makefile
- WORKSPACE
- bazeldnf/deps.bzl
- cmd/BUILD.bazel
- hack/prepare-release.sh
With the recent changes, bazeldnf/deps.bzl import preambles changed. Reflecting this in the release script.
> Adjust release script to write the correct deps

- .github/workflows/buildifier.yaml
- .github/workflows/linter.yaml
- BUILD.bazel
- Makefile
- WORKSPACE
- bazeldnf/toolchain.bzl
- build_deps.bzl
- def.bzl
- deps.bzl
- internal/bazeldnf.bzl
- internal/rpm.bzl
- internal/rpmtree.bzl
- internal/xattrs.bzl
Introducing linters in CI, now we run both buildifier and gazelle during CI to make sure we have no pending changes
> Adding linters to CI

- pkg/rpm/tar.go
This code looks like it was intended to use the tar file implementation in the go-rpmutils PR that this repo is using, but the internal tar implementation never migrated to this.  As of now, this code is never used anywhere and can be safely removed
> Remove unused RPMReader method

- MODULE.bazel
- go.mod
- go.sum
- pkg/rpm/rpm.go
- pkg/sat/BUILD.bazel
- pkg/sat/sat.go
- pkg/sat/sat_determinsitic_test.go
This PR will make the output of the sat resolver deterministic
> Make sat reproducible

- pkg/reducer/BUILD.bazel
- pkg/reducer/helper_test.go
- pkg/reducer/loader_test.go
- pkg/reducer/reducer_test.go
This change introduces tests for the reducer and loader (separately) using the same underlying helper functions.
> reducer: Add tests for reducer and loader

- MODULE.bazel
- cmd/fetch.go
- cmd/reduce.go
- cmd/resolve.go
- cmd/root.go
- cmd/rpmtree.go
- go.mod
- go.sum
- pkg/reducer/reducer.go
- pkg/repo/BUILD.bazel
- pkg/repo/cache.go
- pkg/repo/fetch.go
- pkg/repo/repo_test.go
*NOTE*: This is a replacement for #89, based on my company fork so I can push force and fix commits.
Changes:
* allow to configure the log level (logrus) through an environmental variable, so we don't need to rebuild the binary each time.
* allow to configure the rpm database cache path, this cache by default is stored relatively to the path where the binary gets called, but this means it can't be shared across multiple workspaces using bazeldnf and the same repos, and also that when multiple OSes are being used conflicts can arise (for instance when mixing centos7 and centos stream 9 while doing a migration). By making the path configurable and relative to XDG paths we can get some isolation. This cache is not used by bazel operations, but by bazeldnf binary when resolving dependency …
> General improvements

- BUILD.bazel
- README.md
- e2e/bazel-bzlmod-lock-file/BUILD.bazel
- e2e/bazel-bzlmod-lock-file/rpms-with-no-name-attribute.json
- e2e/bazel-bzlmod-lock-file/rpms.json
- e2e/bazel-bzlmod-non-legacy-mode/BUILD.bazel
- e2e/bazel-bzlmod-non-legacy-mode/MODULE.bazel
- e2e/bazel-bzlmod-toolchain-from-source/BUILD.bazel
- e2e/bazel-bzlmod-toolchain-from-source/MODULE.bazel
- e2e/bazel-bzlmod/BUILD.bazel
- e2e/bazel-bzlmod/MODULE.bazel
- e2e/bazel-workspace/BUILD.bazel
- pkg/rpm/BUILD.bazel
- pkg/rpm/tar.go
- pkg/rpm/tar_test.go
- test_deps.bzl
If two files have the same name but are found in different subdirectories then tar2files will fail.  An example of this is found in abseil-cpp where there are multiple headers with the same name, but sometimes in different subdirectories of `/usr/include`.
This change tweaks our tarfile handling so as to key our lookup map based on the path minus anything before the expected prefix (this will remove the `bazel-out/...` bits from the paths generated by the tar2files rule.  This provides enough context to avoid the name collisions but is still able to deal with the correct path lookup.
> Fix name collision with tar2files command

- .github/workflows/action.yml
Dropping due to end of support in January 2025.
> Remove CI for bazel 5.x

- cmd/resolve.go
- cmd/rpmtree.go
- pkg/sat/sat.go
- pkg/sat/sat_determinsitic_test.go
- pkg/sat/sat_test.go
In addition to allowing a set of packages that are not allowed, we should allow the scope to be narrowed to a set of packages that is allowed.  This change adds the `--only-allow` option to both `resolve` and `rpmtree` commands to achieve this outcome.
> Add allow-list support to resolve and rpmtree

- cmd/BUILD.bazel
- cmd/reduce.go
- cmd/resolve.go
- cmd/resolve_helper.go
- cmd/rpmtree.go
- pkg/reducer/reducer.go
This change contains a few minor refactorings to consolidate a few common patterns and avoid having to make changes in multiple places while evolving the code base.
> Minor refactorings to consolidate common patterns

- cmd/reduce.go
- cmd/resolve_helper.go
- pkg/reducer/reducer.go
- pkg/reducer/reducer_test.go
In some cases we might have packages that are missing and we wish to ignore them in the grand scheme of things.  This knob allows us to ignore packages (specified or dependencies) that are missing and to otherwise just continue about our business.
> Allow us to ignore missing packages when resolving

- pkg/api/api.go
- pkg/repo/fetch.go
Currently if we have a SHA1 or SHA512 sum we'll fail - the assumption is that the checksums are always SHA256.  This change enables us to work in priority order to (SHA512, SHA256, SHA1) to find a usable checksum and use that instead.
This fixes #29
> Add SHA512 and SHA1 support for downloaded files

- cmd/BUILD.bazel
- cmd/config_helper.go
- cmd/config_helper_test.go
- cmd/lockfile.go
- cmd/root.go
- cmd/rpmtree.go
- pkg/api/bazeldnf/config.go
- pkg/bazel/bazel.go
In order to allow for easy generation of the lockfile to use with the rpmtree tags in the bazel module extension we need to add an additional command for this purpose.
The `lockfile` subcommand is derived from a combination  the `rpmtree` subcommand in conjunction with some work from Manuel Naranjo on a `bzlmod` subcommand.
See https://github.com/rmohr/bazeldnf/pull/96 for the `bzlmod` subcommand implementation.
> Add lockfile command to bazeldnf

- .aspect/bazelrc/bazel6.bazelrc
- .aspect/bazelrc/bazel7.bazelrc
- .aspect/bazelrc/correctness.bazelrc
- .aspect/bazelrc/java.bazelrc
- .aspect/bazelrc/performance.bazelrc
- .github/workflows/action.yml
- MODULE.bazel
- e2e/bazel-bzlmod-lock-file/.bazelrc
- e2e/bazel-bzlmod-non-legacy-mode/.bazelrc
- e2e/bazel-bzlmod-toolchain-from-source/.bazelrc
- e2e/bazel-bzlmod-toolchain-from-source/MODULE.bazel
- e2e/bazel-bzlmod/.bazelrc
This change enables bazel 8 support and drops bazel 6 support for the bzlmod e2e tests.
> Enable bazel 8 support

- cmd/root.go
make sure we switch to BUILD_WORKING_DIRECTORY when running under bazel run, to avoid abspaths leaking into lock files
> bzlmod: make sure to chroot under bazel run

- MODULE.bazel
- README.md
- go.mod
- go.sum
- pkg/repo/BUILD.bazel
- pkg/repo/fetch.go
- pkg/repo/fetch_test.go
This is to support something like an internal mirror (such as Artifactory).
It's possible to use an one by hand-crafting a `repo.yaml` file, but things get tricky if such a mirror requires authentication.
This adds support for basic auth driven by a .netrc file.
> Add .netrc support

- cmd/config_helper.go
- cmd/config_helper_test.go
- e2e/bazel-bzlmod-lock-file-from-args/bazeldnf-lock.json
- e2e/bazel-bzlmod-lock-file/rpms-with-no-name-attribute.json
- e2e/bazel-bzlmod-lock-file/rpms.json
- e2e/bzlmod-toolchain-circular-dependencies/bazeldnf-lock.json
- internal/rpm.bzl
- pkg/api/api.go
- pkg/api/bazeldnf/config.go
- pkg/bazel/bazel.go
The underlying downloader that we use when setting up repositories should use integrity instead of SHA256 as it works for SHA512 and SHA1 hashes as well.
> Use integrity instead of sha256 for RPMs

- bazeldnf/extensions.bzl
The existence of the lockfile shouldn't control where we look for the repo file.
> Calculate path to repofile correctly

- bazeldnf/extensions.bzl
- internal/rpm.bzl
Depending on the consumption model, users may need to have a stable set of targets and repository rules to depend on even if the underlying RPMs are missing.  This change is the other side of allowing some of our RPM targets to be missing: if they are missing we can generate dummy repository rules so that we get stable deps.
> Add null repository rule for missing RPMs

- bazeldnf/extensions.bzl
If we don't watch the lock file and we update it (eg: with bazel run) it'll fail to get noticed.
> Watch the lock file

- bazeldnf/extensions.bzl
- bazeldnf/private/lock-file-helpers.bzl
In order to be able to deal with multiple architectures it's desirable to be able to specify the architecture for specific bazeldnf repositories instead of just assuming a default of x86_64.
> Enable use of architecture for config extension

- BUILD.bazel
- MODULE.bazel
- Makefile
- e2e/bazel-bzlmod-lock-file/BUILD.bazel
- e2e/bazel-bzlmod-lock-file/MODULE.bazel
- e2e/bazel-bzlmod-toolchain-from-source/BUILD.bazel
- e2e/bazel-bzlmod-toolchain-from-source/MODULE.bazel
- e2e/bazel-bzlmod/BUILD.bazel
- e2e/bazel-bzlmod/MODULE.bazel
- e2e/bazel-workspace/BUILD.bazel
- e2e/bazel-workspace/WORKSPACE
- internal/rpm.bzl
* rpm_repository is giving annoying warnings in sha256 mode
* watch files in repository_ctx requires bazel 7.x, so let's restrict bzlmod to at least this version
* add missing tests in Makefile wrapper
* add missing import of rules_cc
> Several small non related fixes

- internal/rpm.bzl
- pkg/rpm/BUILD.bazel
- pkg/rpm/tar_test.go
Stop calling the artifact downloaded from the internet downloaded, instead call it by it's URL basename, this is more human friendly when debugging what's going on, also makes testing easier
> rpm: stop calling things downloaded

- bazeldnf/extensions.bzl
The existing implementation only works correctly if you're in the root directory.  Instead, we should use repository_ctx.path() to correctly resolve the paths that we use for the lockfile and repo.yaml.
> Fix paths to repo.yaml and lockfile

- bazeldnf/extensions.bzl
This enable us to drive these via other dependencies, make aliases to them, etc.
> Make fetch-repo and update-lock-file publically visible

- cmd/lockfile.go
- cmd/resolve.go
- cmd/rpmtree.go
- internal/rpm.bzl
- pkg/reducer/helper_test.go
- pkg/sat/sat_test.go
Sometimes RPM rules are on non-public locations. Add .netrc support to RPM rules.
RPM rules now supports the usual pattern:
```
rpm(
...,
auth_patterns = {
"storage.cloudprovider.com": "Bearer <password>"
}
)
```
> Add auth_patterns support to RPM rule

- cmd/xattr.go
- pkg/xattr/xattr.go
Newer bazel versions tar archives do not always start with `./` anymore but have just no prefix. Ensure that xattr can deal with paths starting with `./` but also without a prefix.
> Make xattr more flexible on different tar formats

- cmd/root.go
- internal/rpmtree.bzl
On some platforms, the `tar2files` operation fails with the error "error=7, Argument list too long" when extracting RPMs with a large number of files (e.g., Boost's ~14K files) by passing them directly as command-line arguments. To circumvent this, we supply a single text file containing the list of files to be extracted. This optimization is applied only when the RPM contains more than 100 files, minimizing overhead for smaller RPMs.
Change-Id: I5ae84078ccddd7e948d0e5a9faa2583ca7217cf5
> Support params file for tar2files command

- internal/BUILD.bazel
- internal/rpmtree.bzl
In some cases there's a `/` at the end of `bin_dir.path` and in some cases there isn't.  Using `paths.join()` should deal properly with both cases.
note: this deals with a breakage caused by PR #140
> Do proper path join for strip_prefix

- tools/integrity.bzl
- tools/version.bzl
This change pulls the updated tools versions as v0.99.1 by default.
> Update default tools versions

- cmd/resolve_helper.go
- pkg/sat/sat.go
- pkg/sat/sat_determinsitic_test.go
- pkg/sat/sat_test.go
- tools/integrity.bzl
- tools/version.bzl
This change breaks the SAT solver into two separate loading and resolving steps which will make it easier to test the pieces individually.  The data tracked for the SAT solver is also separated into a distinct Model type which is built up by the Loader and consumed by the Resolver.
> Break down the SAT solver into separate loading and resolving steps
